### ISSUE TITLE
AppImage not launching on LMDE 6: step: "CreateLocalSocket", error: Read-only file system

### ISSUE THREAD

**Issue by ZhaoZuohong** [Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop#35]
[log-2023-10-05T19-55-09.log](https://github.com/Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Electron/files/12817983/log-2023-10-05T19-55-09.log)

**Comment by Goodjooy** [comment]
Did you try run ceobe canteen with sudo ?

**Comment by ZhaoZuohong** [comment]
我从 Release 下载了 CeobeCanteenDesktop v1.0.1 的 AppImage，用 sudo 运行，还是有问题：

```plaintext
  2023-10-07T13:16:03.976853Z  INFO ceobe_canteen_desktop::setup::logger: step: "StartUpLogger", path: "/root/.config/com.ceobe-canteen.desktop/logs"
    at src/setup/logger.rs:46 on main

  2023-10-07T13:16:03.977002Z  INFO ceobe_canteen_desktop::single_instance: step: "NotListenCeobeFind"
    at src/single_instance.rs:74 on main
    in ceobe_canteen_desktop::single_instance::SingletonClient

  2023-10-07T13:16:04.297768Z ERROR ceobe_canteen_desktop::single_instance: step: "CreateLocalSocket", error: Read-only file system (os error 30)
    at src/single_instance.rs:22 on 
    in ceobe_canteen_desktop::single_instance::SingletonService
```

**Comment by Goodjooy** [comment]
有试过 deb安装包吗？
LMDE 6 是基于Debian的，deb安装包应该也能使用

**Comment by ZhaoZuohong** [comment]
安装 deb 包之后运行，会报找不到 `libssl.so.1.1` 的错：

```plaintext
ceobe-canteen: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

用 distrobox 跑了一个 Debian 11 的容器，在里面安装 deb 包，可以运行。跑 AppImage，还是报 `Read-only file system` 的错。

**Comment by Goodjooy** [comment]
> 安装 deb 包之后运行，会报找不到 `libssl.so.1.1` 的错：
> 
> ```plaintext
> ceobe-canteen: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
> ```
> 
> 用 distrobox 跑了一个 Debian 11 的容器，在里面安装 deb 包，可以运行。跑 AppImage，还是报 `Read-only file system` 的错。

这个好像是因为系统内置openssl 版本上到3.0了，版本不兼容

**Comment by Goodjooy** [comment]
作为暂时修复方案，我将linux 中的单例模式代码暂时取消了，并且将 native-tls 替换为 rustls, 也许能解决你碰到的问题

**Comment by Goodjooy** [comment]
似乎ci中macos 签名出现了些问题，但是 unbuntu的打包已经提交了，你也许可以先试试

https://github.com/Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop/releases/tag/untagged-2c484d93e95d07262e7c

**Comment by ZhaoZuohong** [comment]
> https://github.com/Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop/releases/tag/untagged-2c484d93e95d07262e7c

这个链接 404 了

**Comment by Goodjooy** [comment]
> > https://github.com/Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop/releases/tag/untagged-2c484d93e95d07262e7c
> 
> 这个链接 404 了

现在呢？刚刚是draft无法访问 ：）

**Comment by ZhaoZuohong** [comment]
还是 404，不过看到有 Pre-release v1.0.2

**Comment by Goodjooy** [comment]
https://github.com/Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop/releases/tag/tauri-v1.0.2-build.56.1

**Comment by ZhaoZuohong** [comment]
没有问题了，在 Debian 11、LMDE 6（基于 Debian 12）下，AppImage 和 DEB 都能正常运行。

非常感谢！
