### ISSUE TITLE
[FEATURE]通知弹窗修改

### ISSUE THREAD

**Issue by Levin-7** [Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop#47]
## Why need this feature | 为什么需要这个新特性
1.显示时间太长（或者说不消失）
2.设计与系统冲突

## Describe the solution you'd like | 你希望这个新特征是怎样的
1.通知推送一定时间后消失
2.使用系统自带通知（大概就像Chrome插件版那个样子）

## Additional context | 补充内容
可选择性修改弹窗内容（如自定义文本格式，是否显示图片等等）

**Comment by Goodjooy** [comment]
感谢您使用小刻食堂！


不使用系统弹窗当初有以下原因
- 系统消息弹窗不美观
- 跨平台接口的系统消息目前只支持纯文本，不支持带图片展示

我认为在弹窗选项中添加使用系统通知支持是个不错的主意 

弹窗一直保持不消失也确实是个问题，这个应该是个bug，这个问题我们会尽快修复

关于自定义弹窗样式，我认为单独开一个issue可能能更详细描述？

在添加更多设置选项之前，也许需要更改当前的设置展示界面 @phidiaLam

**Comment by phidiaLam** [comment]
> * 的系统消息目前只

请问一下，自定义文本格式具体表现是什么呢？

**Comment by Levin-7** [comment]
> > * 的系统消息目前只
> 
> 请问一下，自定义文本格式具体表现是什么呢？

简单说有新通知时文本是“小刻蹲到饼了”（我记性不太好，大概就是这个意思）
上述双引号内的这部分（当然这方面不改也行，毕竟你永远不知道用户是怎么把软件玩坏的）

**Comment by Goodjooy** [comment]
> ## Why need this feature | 为什么需要这个新特性
> 
> 1.显示时间太长（或者说不消失） 2.设计与系统冲突
> ## Describe the solution you'd like | 你希望这个新特征是怎样的
> 
> 1.通知推送一定时间后消失 2.使用系统自带通知（大概就像Chrome插件版那个样子）
> ## Additional context | 补充内容
> 
> 可选择性修改弹窗内容（如自定义文本格式，是否显示图片等等）

- 新饼推送弹窗显示现在将会显示10s 后关闭
- 现在新饼推送可以选择使用系统消息推送

以上功能已于1.0.3 添加

如果你认为自定义弹窗内容仍然是个必要的Feature , 请在另一个 issue 中进行更深入讨论
