### ISSUE TITLE
[BUG]检查更新失败

### ISSUE THREAD

**Issue by Levin-7** [Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop#53]
## Describe the bug | 描述 BUG
存在新版本时检查更新提示无更新版本

## To Reproduce | 如何复现
在有新版本时检查更新

## Screenshots | 截图

![屏幕截图 2023-10-09 112458](https://github.com/Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop/assets/101990094/af41dc49-4bfb-497e-ae55-7a3677875700)

## System Information | 系统信息
 - OS 系统: Windows
 - Version 系统版本:10 22H2 (19045.3208) 
 - App Version App版本: Ver.1.0.1

## Additional context | 补充说明的内容
这玩意不发新包谁知道有问题啊...

**Comment by Goodjooy** [comment]
额？请问是指
1.0.2 发布了但是检查更新没检查到吗？
还是别的什么问题？

**Comment by Goodjooy** [comment]
如果是1.0.2 更新没有收到，那有以下几个原因
1. 1.0.2 CI 打包 MacOS 安装包时出现错误，导致最终只打包出了linux 与 windows 的安装包
2. release 上面的1.0.2 是手动发布的，用于暂时供 #35 的用户查看问题是否已经解决
3. 发布版本是管理员手动发布的，在 1.0.2 CI 打包问题修复后应该就会尽快发布新版本了

**Comment by Levin-7** [comment]
是1.0.2发布之后没检查到
不是新BUG就好

**Comment by Levin-7** [comment]
我把它关了干啥...

**Comment by Levin-7** [comment]
已确认此问题于Ver.1.0.2修复
