### ISSUE TITLE
列表在无详细时间新饼来后有时间新饼再进入的时候排序错误[BUG]

### ISSUE THREAD

**Issue by phidiaLam** [Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop#54]
## Describe the bug | 描述 BUG
比如公告、官网等无详细时间并来的时候，会出现数据重复
具体列表表现为：
无详细时间的饼（这个与前面无详细时间饼一致）
有详细时间的饼（最新的）
无详细时间的饼（这个位置正常）

## To Reproduce | 如何复现
复现BUG的步骤
1. 等待无详细时间新饼来
2. 等待有详细时间新饼来

## Expected behavior | 预期的行为
正常排序：
有详细时间的饼
无详细时间的饼

## Screenshots | 截图
![{F9F92856-CD0A-4b97-8BAE-4D5FE947641F}](https://github.com/Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Desktop/assets/67498817/e2562dec-5f2e-435b-8359-c40edbd08c2a)

## System Information | 系统信息
 - OS 系统: Windows
 - Version 系统版本: 22H2
 - App Version App版本: 1.0.1

**Comment by Goodjooy** [comment]
可能完成修复
